# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true
  parse_block_html: true

# Permalinks
permalink:      pretty

# Server
source:         "."
destination:    ./_gh_pages
host:           0.0.0.0
port:           9001
baseurl:        "/PowerBI-visuals"
url:            "https://microsoft.github.io"
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - assets/scss/
  - build/
  - js/
  - node_modules/
  - scss/
  - Gemfile
  - Gemfile.lock
  - package.js
  - package.json
  - package-lock.json
  - README.md

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Social
title:              PowerBI Custom Visuals
description:        "PowerBI Custom Visuals Developers Documenation"    
authors:            "Microsoft"
blog:               "https://powerbi.microsoft.com/en-us/blog/"
appsource:          "https://appsource.microsoft.com/en-us/marketplace/apps?product=power-bi-visuals"

# Custom variables
current_version:      2.6
repo:                 "https://github.com/Microsoft/PowerBI-visuals-tools"
ga_id:                "UA-116683883-1"            

#disqus:
#  shortname:        "powerbi-custom-visuals"

#github comments:
github_comments_repository: Microsoft/powerbi-visuals


cdn:
  bootstrap_css:    "https://ajax.aspnetcdn.com/ajax/bootstrap/4.1.1/css/bootstrap.min.css"
  css_hash:         "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
  bootstrap_js:               "https://ajax.aspnetcdn.com/ajax/bootstrap/4.1.1/bootstrap.min.js"
  bootstrap_js_hash:          "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
  jquery_js:        "https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"

toc:
  min_level:        1
  max_level:        6

exclude2: [node_modules, README.md]